# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94b301797c89b65159a6b6f8f11440a4b940486ca6cf8371db0dcedaea2c4217ae5dfee9f6df3c4a0201fc32e031efb1f9799db46639860ce22ca54c82ca5cda

test:
  secret_key_base: 3aeb326ae3b8f69b07d84eddf71e90910d4e055c634edf4fab686fddf58b03610c8c3b464d23b6866fc61bd10b098a61352fb22c1c621b21b001751d8962a6b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
